import DashboardLayout from "../dashboard/layout";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <DashboardLayout>{children}</DashboardLayout>;
}