/*
  Warnings:

  - Changed the type of `severity` on the `MedError` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.
  - Changed the type of `errorType` on the `MedError` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.
  - Changed the type of `subErrorType` on the `MedError` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- CreateEnum
CREATE TYPE "Severity" AS ENUM ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I');

-- CreateEnum
CREATE TYPE "ErrorType" AS ENUM ('PRESCRIBING', 'TRANSCRIPTION', 'PRE_DISPENSING', 'DISPENSING', 'ADMINISTRATION');

-- CreateEnum
CREATE TYPE "SubErrorTypePrescribing" AS ENUM ('UNSPECIFIED_STRENGTH', 'UNSPECIFIED_FORM', 'UNSPECIFIED_QUANTITY', 'UNSPECIFIED_USAGE', 'INCORRECT_DOSAGE', 'CHANGED_USAGE_FROM_PREVIOUS', 'NAME_MISMATCH', 'DUPLICATE_SAME_PRESCRIPTION', 'DUPLICATE_DIFFERENT_CLINIC', 'INCORRECT_DRUG_NAME', 'DRUG_NOT_AVAILABLE', 'TWO_STRENGTHS_SAME_PRESCRIPTION', 'ABNORMAL_QUANTITY', 'CANNOT_ADMINISTER', 'UNCLEAR_INSTRUCTION', 'NON_STANDARD_ABBREVIATION', 'ALLERGY_HISTORY', 'DRUG_INTERACTION', 'RESTRICTED_DRUG', 'CONTRAINDICATED_PREGNANCY', 'OMITTED_NECESSARY_DRUG', 'INCORRECT_FOR_DISEASE', 'PATIENT_REFUSED', 'LACK_LAB_INFO', 'CONTRAINDICATED_OR_WARNING');

-- CreateEnum
CREATE TYPE "SubErrorTypeTranscribing" AS ENUM ('INCORRECT_TYPE', 'INCORRECT_QUANTITY', 'INCOMPLETE_ITEMS', 'INCORRECT_STRENGTH', 'INCORRECT_LABEL', 'INCORRECT_FORM', 'INCORRECT_USAGE', 'INCORRECT_DOSAGE', 'COPIED_UNORDERED_DRUG', 'NOT_SENT_COPY_ORDER', 'INCORRECT_PERSON');

-- CreateEnum
CREATE TYPE "SubErrorTypePreDispensing" AS ENUM ('INCORRECT_TYPE', 'INCORRECT_QUANTITY', 'INCOMPLETE_ITEMS', 'INCORRECT_STRENGTH', 'INCORRECT_LABEL', 'INCORRECT_FORM', 'MIXED_WITH_OTHER_PATIENT', 'INCORRECT_DOSAGE', 'EXPIRED_OR_DETERIORATED', 'MIXED_DRUGS', 'INCORRECT_PATIENT_MATCH');

-- CreateEnum
CREATE TYPE "SubErrorTypeDispensing" AS ENUM ('INCORRECT_TYPE', 'INCORRECT_FORM', 'INCORRECT_STRENGTH', 'INCORRECT_QUANTITY', 'INCOMPLETE_ITEMS', 'INCORRECT_OR_MISSING_LABEL', 'INCORRECT_PERSON_OR_MIXED', 'UNORDERED_DRUG', 'INCORRECT_USAGE', 'DUPLICATE_DRUG', 'INCORRECT_DOSAGE', 'DELAYED_DISPENSING', 'EXPIRED_OR_DETERIORATED', 'INCORRECT_LOCKER');

-- CreateEnum
CREATE TYPE "SubErrorTypeAdministration" AS ENUM ('INCORRECT_PERSON', 'INCORRECT_TYPE', 'INCORRECT_DOSAGE_OR_STRENGTH', 'DUPLICATE_OR_UNORDERED_DRUG', 'INCORRECT_OR_MISSED_TIME', 'INCORRECT_ROUTE_OR_SIDE', 'INCORRECT_TECHNIQUE', 'ALLERGY_OR_CONTRAINDICATION', 'INCORRECT_USAGE', 'EXPIRED_OR_UNSTABLE');

-- AlterTable
ALTER TABLE "MedError" DROP COLUMN "severity",
ADD COLUMN     "severity" "Severity" NOT NULL,
DROP COLUMN "errorType",
ADD COLUMN     "errorType" "ErrorType" NOT NULL,
DROP COLUMN "subErrorType",
ADD COLUMN     "subErrorType" "SubErrorTypePrescribing" NOT NULL;
